on:
  push:
    branches:
      - 'master'
  pull_request:

name: CI

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [latest, 20.x, 18.x, 16.x]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.event.pull_request.number || github.ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          {
            echo 'STORE_PATH<<EOF'
            pnpm store path --silent
            echo 'EOF'
          } >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: EsLint
        run: pnpm lint

      - name: Stylelint
        run: pnpm stylelint
